#!/bin/bash

source `dirname $0`/environment

${BIN}/ovs-vsctl -- --if-exists del-br br0
${BIN}/ovs-vsctl add-br br0
#${BIN}/ovs-vsctl add-port br0 ${OVS_IFACE}
${BIN}/ovs-vsctl add-port br0 lisp0 -- set Interface lisp0 type=lisp options:remote_ip=flow options:key=flow
${BIN}/ovs-vsctl set bridge br0 protocol=${OVS_PROTO}
${BIN}/ovs-vsctl show

BR0_ETHER=`ip link show br0 | grep ether | awk '{ print $2; }'`

${BIN}/ovs-ofctl -O ${OVS_PROTO} show br0
${BIN}/ovs-ofctl -O ${OVS_PROTO} del-flows br0
${BIN}/ovs-ofctl -O ${OVS_PROTO} add-flow br0 "priority=1,in_port=1,tun_id=0x10203,action=mod_dl_dst:${BR0_ETHER},output:LOCAL"
${BIN}/ovs-ofctl -O ${OVS_PROTO} add-flow br0 "priority=1,in_port=LOCAL,dl_type=0x0800,vlan_tci=0,nw_dst=${LISP_PEER_EID}/32,action=set_field:0x10203->tun_id,set_field:${LISP_PEER_RLOC}->tun_dst,output:1"
${BIN}/ovs-ofctl -O ${OVS_PROTO} add-flow br0 "priority=0,action=NORMAL"

ifconfig br0 ${LISP_LOCAL_EID}/24 up

# Set static ARP entries, to avoid ARP lookups to make debugging easier
arp -f
