#!/bin/bash

source `dirname $0`/environment

modprobe -r openvswitch
modprobe -q libcrc32c
insmod ${BUILD_DIR}/datapath/linux/openvswitch.ko
insmod ${BUILD_DIR}/datapath/linux/vport-lisp.ko

rm -f /usr/local/etc/openvswitch/conf.db
${BIN}/ovsdb-tool create /usr/local/etc/openvswitch/conf.db ${BUILD_DIR}/vswitchd/vswitch.ovsschema

${SBIN}/ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock \
                     --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
                     --private-key=db:Open_vSwitch,SSL,private_key \
                     --certificate=db:Open_vSwitch,SSL,certificate \
                     --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert \
                     --pidfile --detach

${BIN}/ovs-vsctl --no-wait init

${SBIN}/ovs-vswitchd --pidfile --detach
