#!/bin/bash

source `dirname $0`/environment

modprobe -r openvswitch
insmod ${BUILD_DIR}/datapath/linux/openvswitch.ko

rm -f /usr/local/etc/openvswitch/conf.db
${BIN}/ovsdb-tool create /usr/local/etc/openvswitch/conf.db ${BUILD_DIR}/vswitchd/vswitch.ovsschema

${SBIN}/ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock \
                     --remote=db:Open_vSwitch,manager_options \
                     --private-key=db:SSL,private_key \
                     --certificate=db:SSL,certificate \
                     --bootstrap-ca-cert=db:SSL,ca_cert \
                     --pidfile --detach

${BIN}/ovs-vsctl --no-wait init

${SBIN}/ovs-vswitchd --pidfile --detach
