#!/bin/bash

source `dirname $0`/environment

tunctl -t ${VM_IFACE}
${BIN}/ovs-vsctl -- --if-exists del-br br0
${BIN}/ovs-vsctl add-br br0
${BIN}/ovs-vsctl add-port br0 ${VM_IFACE} tag=0
${BIN}/ovs-vsctl add-port br0 ${OVS_IFACE} tag=31
${BIN}/ovs-vsctl add-port br0 vxl0 tag=0 -- set Interface vxl0 type=vxlan options:remote_ip=192.168.127.2
${BIN}/ovs-vsctl add-port br0 vlan tag=31 -- set Interface vlan type=internal
${BIN}/ovs-vsctl show

${BIN}/ovs-ofctl del-flows br0
${BIN}/ovs-ofctl add-flows br0 flow_table_vxlan

ifconfig br0 up
ifconfig ${VM_IFACE} up
ifconfig ${OVS_IFACE} 0.0.0.0
ifconfig vlan ${OVS_PREFIX} up
